/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarteiraRouteImport } from './routes/carteira'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ConfirmacaoRouteImport } from './routes/confirmacao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlanejarRouteImport } from './routes/planejar'
import { Route as RhRouteImport } from './routes/rh'
import { Route as RhIndexRouteImport } from './routes/rh.index'
import { Route as RhCashbackRouteImport } from './routes/rh.cashback'
import { Route as RhConfiguracoesRouteImport } from './routes/rh.configuracoes'
import { Route as RhCreditosRouteImport } from './routes/rh.creditos'
import { Route as RhEsgRouteImport } from './routes/rh.esg'
import { Route as RhIntegracoesRouteImport } from './routes/rh.integracoes'
import { Route as RhIntelligenceRouteImport } from './routes/rh.intelligence'
import { Route as RhMobilidadeRouteImport } from './routes/rh.mobilidade'
import { Route as RhPoliticasRouteImport } from './routes/rh.politicas'
import { Route as RhRelatoriosRouteImport } from './routes/rh.relatorios'
import { Route as RhTransacoesRouteImport } from './routes/rh.transacoes'
import { Route as ApiMobilitySearchRouteImport } from './routes/api/mobility/search'
import { Route as RhColaboradoresIndexRouteImport } from './routes/rh.colaboradores.index'
import { Route as RhColaboradoresIdRouteImport } from './routes/rh.colaboradores.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraRoute = CarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacaoRoute = ConfirmacaoRouteImport.update({
  id: '/confirmacao',
  path: '/confirmacao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejarRoute = PlanejarRouteImport.update({
  id: '/planejar',
  path: '/planejar',
  getParentRoute: () => rootRouteImport,
} as any)
const RhRoute = RhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => rootRouteImport,
} as any)
const RhIndexRoute = RhIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RhRoute,
} as any)
const RhCashbackRoute = RhCashbackRouteImport.update({
  id: '/cashback',
  path: '/cashback',
  getParentRoute: () => RhRoute,
} as any)
const RhConfiguracoesRoute = RhConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => RhRoute,
} as any)
const RhCreditosRoute = RhCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => RhRoute,
} as any)
const RhEsgRoute = RhEsgRouteImport.update({
  id: '/esg',
  path: '/esg',
  getParentRoute: () => RhRoute,
} as any)
const RhIntegracoesRoute = RhIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => RhRoute,
} as any)
const RhIntelligenceRoute = RhIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => RhRoute,
} as any)
const RhMobilidadeRoute = RhMobilidadeRouteImport.update({
  id: '/mobilidade',
  path: '/mobilidade',
  getParentRoute: () => RhRoute,
} as any)
const RhPoliticasRoute = RhPoliticasRouteImport.update({
  id: '/politicas',
  path: '/politicas',
  getParentRoute: () => RhRoute,
} as any)
const RhRelatoriosRoute = RhRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => RhRoute,
} as any)
const RhTransacoesRoute = RhTransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => RhRoute,
} as any)
const ApiMobilitySearchRoute = ApiMobilitySearchRouteImport.update({
  id: '/api/mobility/search',
  path: '/api/mobility/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RhColaboradoresIndexRoute = RhColaboradoresIndexRouteImport.update({
  id: '/colaboradores/',
  path: '/colaboradores/',
  getParentRoute: () => RhRoute,
} as any)
const RhColaboradoresIdRoute = RhColaboradoresIdRouteImport.update({
  id: '/colaboradores/$id',
  path: '/colaboradores/$id',
  getParentRoute: () => RhRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carteira': typeof CarteiraRoute
  '/checkout': typeof CheckoutRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/login': typeof LoginRoute
  '/planejar': typeof PlanejarRoute
  '/rh': typeof RhRouteWithChildren
  '/rh/cashback': typeof RhCashbackRoute
  '/rh/configuracoes': typeof RhConfiguracoesRoute
  '/rh/creditos': typeof RhCreditosRoute
  '/rh/esg': typeof RhEsgRoute
  '/rh/integracoes': typeof RhIntegracoesRoute
  '/rh/intelligence': typeof RhIntelligenceRoute
  '/rh/mobilidade': typeof RhMobilidadeRoute
  '/rh/politicas': typeof RhPoliticasRoute
  '/rh/relatorios': typeof RhRelatoriosRoute
  '/rh/transacoes': typeof RhTransacoesRoute
  '/rh/': typeof RhIndexRoute
  '/api/mobility/search': typeof ApiMobilitySearchRoute
  '/rh/colaboradores/$id': typeof RhColaboradoresIdRoute
  '/rh/colaboradores/': typeof RhColaboradoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carteira': typeof CarteiraRoute
  '/checkout': typeof CheckoutRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/login': typeof LoginRoute
  '/planejar': typeof PlanejarRoute
  '/rh/cashback': typeof RhCashbackRoute
  '/rh/configuracoes': typeof RhConfiguracoesRoute
  '/rh/creditos': typeof RhCreditosRoute
  '/rh/esg': typeof RhEsgRoute
  '/rh/integracoes': typeof RhIntegracoesRoute
  '/rh/intelligence': typeof RhIntelligenceRoute
  '/rh/mobilidade': typeof RhMobilidadeRoute
  '/rh/politicas': typeof RhPoliticasRoute
  '/rh/relatorios': typeof RhRelatoriosRoute
  '/rh/transacoes': typeof RhTransacoesRoute
  '/rh': typeof RhIndexRoute
  '/api/mobility/search': typeof ApiMobilitySearchRoute
  '/rh/colaboradores/$id': typeof RhColaboradoresIdRoute
  '/rh/colaboradores': typeof RhColaboradoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carteira': typeof CarteiraRoute
  '/checkout': typeof CheckoutRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/login': typeof LoginRoute
  '/planejar': typeof PlanejarRoute
  '/rh': typeof RhRouteWithChildren
  '/rh/cashback': typeof RhCashbackRoute
  '/rh/configuracoes': typeof RhConfiguracoesRoute
  '/rh/creditos': typeof RhCreditosRoute
  '/rh/esg': typeof RhEsgRoute
  '/rh/integracoes': typeof RhIntegracoesRoute
  '/rh/intelligence': typeof RhIntelligenceRoute
  '/rh/mobilidade': typeof RhMobilidadeRoute
  '/rh/politicas': typeof RhPoliticasRoute
  '/rh/relatorios': typeof RhRelatoriosRoute
  '/rh/transacoes': typeof RhTransacoesRoute
  '/rh/': typeof RhIndexRoute
  '/api/mobility/search': typeof ApiMobilitySearchRoute
  '/rh/colaboradores/$id': typeof RhColaboradoresIdRoute
  '/rh/colaboradores/': typeof RhColaboradoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carteira'
    | '/checkout'
    | '/confirmacao'
    | '/login'
    | '/planejar'
    | '/rh'
    | '/rh/cashback'
    | '/rh/configuracoes'
    | '/rh/creditos'
    | '/rh/esg'
    | '/rh/integracoes'
    | '/rh/intelligence'
    | '/rh/mobilidade'
    | '/rh/politicas'
    | '/rh/relatorios'
    | '/rh/transacoes'
    | '/rh/'
    | '/api/mobility/search'
    | '/rh/colaboradores/$id'
    | '/rh/colaboradores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carteira'
    | '/checkout'
    | '/confirmacao'
    | '/login'
    | '/planejar'
    | '/rh/cashback'
    | '/rh/configuracoes'
    | '/rh/creditos'
    | '/rh/esg'
    | '/rh/integracoes'
    | '/rh/intelligence'
    | '/rh/mobilidade'
    | '/rh/politicas'
    | '/rh/relatorios'
    | '/rh/transacoes'
    | '/rh'
    | '/api/mobility/search'
    | '/rh/colaboradores/$id'
    | '/rh/colaboradores'
  id:
    | '__root__'
    | '/'
    | '/carteira'
    | '/checkout'
    | '/confirmacao'
    | '/login'
    | '/planejar'
    | '/rh'
    | '/rh/cashback'
    | '/rh/configuracoes'
    | '/rh/creditos'
    | '/rh/esg'
    | '/rh/integracoes'
    | '/rh/intelligence'
    | '/rh/mobilidade'
    | '/rh/politicas'
    | '/rh/relatorios'
    | '/rh/transacoes'
    | '/rh/'
    | '/api/mobility/search'
    | '/rh/colaboradores/$id'
    | '/rh/colaboradores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarteiraRoute: typeof CarteiraRoute
  CheckoutRoute: typeof CheckoutRoute
  ConfirmacaoRoute: typeof ConfirmacaoRoute
  LoginRoute: typeof LoginRoute
  PlanejarRoute: typeof PlanejarRoute
  RhRoute: typeof RhRouteWithChildren
  ApiMobilitySearchRoute: typeof ApiMobilitySearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira': {
      id: '/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof CarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacao': {
      id: '/confirmacao'
      path: '/confirmacao'
      fullPath: '/confirmacao'
      preLoaderRoute: typeof ConfirmacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejar': {
      id: '/planejar'
      path: '/planejar'
      fullPath: '/planejar'
      preLoaderRoute: typeof PlanejarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh': {
      id: '/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof RhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/': {
      id: '/rh/'
      path: '/'
      fullPath: '/rh/'
      preLoaderRoute: typeof RhIndexRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/cashback': {
      id: '/rh/cashback'
      path: '/cashback'
      fullPath: '/rh/cashback'
      preLoaderRoute: typeof RhCashbackRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/configuracoes': {
      id: '/rh/configuracoes'
      path: '/configuracoes'
      fullPath: '/rh/configuracoes'
      preLoaderRoute: typeof RhConfiguracoesRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/creditos': {
      id: '/rh/creditos'
      path: '/creditos'
      fullPath: '/rh/creditos'
      preLoaderRoute: typeof RhCreditosRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/esg': {
      id: '/rh/esg'
      path: '/esg'
      fullPath: '/rh/esg'
      preLoaderRoute: typeof RhEsgRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/integracoes': {
      id: '/rh/integracoes'
      path: '/integracoes'
      fullPath: '/rh/integracoes'
      preLoaderRoute: typeof RhIntegracoesRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/intelligence': {
      id: '/rh/intelligence'
      path: '/intelligence'
      fullPath: '/rh/intelligence'
      preLoaderRoute: typeof RhIntelligenceRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/mobilidade': {
      id: '/rh/mobilidade'
      path: '/mobilidade'
      fullPath: '/rh/mobilidade'
      preLoaderRoute: typeof RhMobilidadeRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/politicas': {
      id: '/rh/politicas'
      path: '/politicas'
      fullPath: '/rh/politicas'
      preLoaderRoute: typeof RhPoliticasRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/relatorios': {
      id: '/rh/relatorios'
      path: '/relatorios'
      fullPath: '/rh/relatorios'
      preLoaderRoute: typeof RhRelatoriosRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/transacoes': {
      id: '/rh/transacoes'
      path: '/transacoes'
      fullPath: '/rh/transacoes'
      preLoaderRoute: typeof RhTransacoesRouteImport
      parentRoute: typeof RhRoute
    }
    '/api/mobility/search': {
      id: '/api/mobility/search'
      path: '/api/mobility/search'
      fullPath: '/api/mobility/search'
      preLoaderRoute: typeof ApiMobilitySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/colaboradores/': {
      id: '/rh/colaboradores/'
      path: '/colaboradores'
      fullPath: '/rh/colaboradores/'
      preLoaderRoute: typeof RhColaboradoresIndexRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/colaboradores/$id': {
      id: '/rh/colaboradores/$id'
      path: '/colaboradores/$id'
      fullPath: '/rh/colaboradores/$id'
      preLoaderRoute: typeof RhColaboradoresIdRouteImport
      parentRoute: typeof RhRoute
    }
  }
}

interface RhRouteChildren {
  RhCashbackRoute: typeof RhCashbackRoute
  RhConfiguracoesRoute: typeof RhConfiguracoesRoute
  RhCreditosRoute: typeof RhCreditosRoute
  RhEsgRoute: typeof RhEsgRoute
  RhIntegracoesRoute: typeof RhIntegracoesRoute
  RhIntelligenceRoute: typeof RhIntelligenceRoute
  RhMobilidadeRoute: typeof RhMobilidadeRoute
  RhPoliticasRoute: typeof RhPoliticasRoute
  RhRelatoriosRoute: typeof RhRelatoriosRoute
  RhTransacoesRoute: typeof RhTransacoesRoute
  RhIndexRoute: typeof RhIndexRoute
  RhColaboradoresIdRoute: typeof RhColaboradoresIdRoute
  RhColaboradoresIndexRoute: typeof RhColaboradoresIndexRoute
}

const RhRouteChildren: RhRouteChildren = {
  RhCashbackRoute: RhCashbackRoute,
  RhConfiguracoesRoute: RhConfiguracoesRoute,
  RhCreditosRoute: RhCreditosRoute,
  RhEsgRoute: RhEsgRoute,
  RhIntegracoesRoute: RhIntegracoesRoute,
  RhIntelligenceRoute: RhIntelligenceRoute,
  RhMobilidadeRoute: RhMobilidadeRoute,
  RhPoliticasRoute: RhPoliticasRoute,
  RhRelatoriosRoute: RhRelatoriosRoute,
  RhTransacoesRoute: RhTransacoesRoute,
  RhIndexRoute: RhIndexRoute,
  RhColaboradoresIdRoute: RhColaboradoresIdRoute,
  RhColaboradoresIndexRoute: RhColaboradoresIndexRoute,
}

const RhRouteWithChildren = RhRoute._addFileChildren(RhRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarteiraRoute: CarteiraRoute,
  CheckoutRoute: CheckoutRoute,
  ConfirmacaoRoute: ConfirmacaoRoute,
  LoginRoute: LoginRoute,
  PlanejarRoute: PlanejarRoute,
  RhRoute: RhRouteWithChildren,
  ApiMobilitySearchRoute: ApiMobilitySearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
